# Generated by Django 5.1.2 on 2024-10-27 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippingaddress',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress'),
        ),
    ]
